import crypto from 'crypto';
import fs from 'fs/promises';
import path from 'path';

const EC_ALGORITHM_DETAILS = {
  name: 'prime256v1', // A common and secure elliptic curve
  // For consistency with openssl generated keys (SEC1 format)
  publicKeyEncoding: { type: 'spki', format: 'pem' } as const,
  privateKeyEncoding: { type: 'sec1', format: 'pem' } as const, // Changed to 'sec1'
};

const AES_ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 96-bit IV for AES-GCM
const AUTH_TAG_LENGTH = 16; // 128-bit authentication tag for AES-GCM

const KEYS_DIR = path.resolve(process.cwd(), 'keys');
const PRIVATE_KEY_PATH = path.join(KEYS_DIR, '.private_key.pem');
const PUBLIC_KEY_PATH = path.join(KEYS_DIR, '.public_key.pem'); // Optional, but good practice

export class ECKeyPair {
  private privateKey: crypto.KeyObject | null = null;
  public publicKey: crypto.KeyObject | null = null;

  constructor() {
    // Keys are initialized to null. They will be loaded or generated by the init() method.
  }

  async init(): Promise<void> {
    await fs.mkdir(KEYS_DIR, { recursive: true });

    let privateKeyPem: string;
    let publicKeyPem: string;

    try {
      // Try to load existing keys
      privateKeyPem = await fs.readFile(PRIVATE_KEY_PATH, 'utf8');
      publicKeyPem = await fs.readFile(PUBLIC_KEY_PATH, 'utf8');
      
      // Explicitly specify format and type when creating KeyObject from PEM
      this.privateKey = crypto.createPrivateKey({ key: privateKeyPem, format: 'pem', type: 'sec1' }); // Explicitly 'sec1'
      this.publicKey = crypto.createPublicKey(publicKeyPem); // Public key is usually SPKI, format 'pem' is fine

      console.log('EC key pair loaded from files.');
    } catch (error) {
      // If files don't exist or are unreadable, generate new keys
      console.warn('EC key pair files not found or unreadable. Generating new keys...');
      
      const keyPairGenerated = crypto.generateKeyPairSync('ec', {
        namedCurve: EC_ALGORITHM_DETAILS.name,
        publicKeyEncoding: EC_ALGORITHM_DETAILS.publicKeyEncoding,
        privateKeyEncoding: EC_ALGORITHM_DETAILS.privateKeyEncoding, // Now uses 'sec1'
      });

      // Directly export the generated KeyObjects to PEM strings
      privateKeyPem = keyPairGenerated.privateKey.export(EC_ALGORITHM_DETAILS.privateKeyEncoding).toString();
      publicKeyPem = keyPairGenerated.publicKey.export(EC_ALGORITHM_DETAILS.publicKeyEncoding).toString();

      this.privateKey = keyPairGenerated.privateKey;
      this.publicKey = keyPairGenerated.publicKey;

      // Save new PEM keys to files
      await fs.writeFile(PRIVATE_KEY_PATH, privateKeyPem, 'utf8');
      await fs.writeFile(PUBLIC_KEY_PATH, publicKeyPem, 'utf8');
      console.log('New EC key pair generated and saved to files.');
    }
  }

  getPublicKeyDER(): Buffer {
    if (!this.publicKey) {
      throw new Error('Public key not initialized. Call init() first.');
    }
    const pem = this.publicKey.export({ type: 'spki', format: 'pem' }) as string;
    const pemHeader = "-----BEGIN PUBLIC KEY-----";
    const pemFooter = "-----END PUBLIC KEY-----";
    const pemContents = pem.replace(pemHeader, "").replace(pemFooter, "").replace(/\s/g, "");
    return Buffer.from(pemContents, 'base64');
  }

  getPublicKeyPEM(): string {
    if (!this.publicKey) {
      throw new Error('Public key not initialized. Call init() first.');
    }
    return this.publicKey.export({ type: 'spki', format: 'pem' }) as string;
  }

  async decrypt(encryptedPayload: string): Promise<string> {
    if (!this.privateKey) {
      throw new Error('Private key not initialized. Call init() first.');
    }
    try {
      // Decode the base64 string to get the JSON string
      const decodedPayload = Buffer.from(encryptedPayload, 'base64').toString('utf8');
      const { iv, encryptedData, ephemeralPublicKey } = JSON.parse(decodedPayload);

      // Convert arrays back to Buffers/Uint8Arrays
      const ivBuffer = Buffer.from(iv);
      const encryptedDataBuffer = Buffer.from(encryptedData);
      const ephemeralPublicKeyBuffer = Buffer.from(ephemeralPublicKey);

      // 1. Create ECDH instance
      const ecdh = crypto.createECDH(EC_ALGORITHM_DETAILS.name);
      
      // Set the server's private key for key derivation.
      // Export the private key to 'sec1' DER format, which is typically what setPrivateKey expects for raw EC keys.
      const serverRawPrivateKey = this.privateKey.export({ format: 'der', type: 'sec1' });
      ecdh.setPrivateKey(serverRawPrivateKey); 

      // 2. Derive shared secret using client's ephemeral public key
      const sharedSecret = ecdh.computeSecret(ephemeralPublicKeyBuffer);

      // 3. Derive AES key from shared secret (e.g., using HKDF or a simple hash)
      const aesKey = crypto.createHash('sha256').update(sharedSecret).digest();

      // 4. Decrypt the actual data using the derived AES key and IV
      const decipher = crypto.createDecipheriv(AES_ALGORITHM, aesKey, ivBuffer);
      
      const ciphertext = encryptedDataBuffer.slice(0, encryptedDataBuffer.length - AUTH_TAG_LENGTH);
      const authTag = encryptedDataBuffer.slice(encryptedDataBuffer.length - AUTH_TAG_LENGTH);
      
      decipher.setAuthTag(authTag);

      let decrypted = decipher.update(ciphertext);
      decrypted = Buffer.concat([decrypted, decipher.final()]);
      
      return decrypted.toString('utf8');
    } catch (error) {
      console.error('Server decryption error:', error);
      throw new Error('Failed to decrypt data on server');
    }
  }

  // Generate a hash for identicon
  getPublicKeyHash(): string {
    if (!this.publicKey) {
      throw new Error('Public key not initialized. Call init() first.');
    }
    const publicKeyDER = this.getPublicKeyDER();
    return crypto.createHash('sha256').update(publicKeyDER).digest('hex');
  }
}

// Global instance
export const serverKeyPair = new ECKeyPair();
// The init() method will be called in server/routes.ts to ensure keys are ready before routes.
